import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { inter } from "@/app/fonts";
import "./globals.css";
import Header from "@/components/header";

export const runtime = "edge";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <ClerkProvider>
         <html lang="en">
            <body
               className={`${inter.className} relative flex min-h-screen flex-col bg-background`}
            >
               <Header />
               <main className="mx-auto w-full max-w-screen-lg p-4">
                  {children}
               </main>
            </body>
         </html>
      </ClerkProvider>
   );
}
