export const predictionPointValues: { [prediction: string]: number } = {
   lover_bodysuit: 5,
   lover_themanjacket: 2,
   lover_guitar_color: 2,
   fearless_dress: 5,
   evermore_dress: 2,
   evermore_champagne_cheer: 5,
   reputation_jumpsuit: 13,
   speak_now_dress: 8,
   red_22_shirt: 7,
   folklore_dress: 8,
   n1989_set: 6,
   surprise_speech: 2,
   surprise_album: 7,
   surprise_song: 7,
   midnights_tshirt_dress: 2,
   midnights_midnight_rain_bodysuit: 3,
   midnights_karma_jacket: 3,
   misc_special_guest: 5,
   misc_unhinged: 5,
};
